version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: fin-man-api-web-app
    container_name: fin-man-api-web-app
    ports:
      - "8080:8080"
    env_file:
      - env/.db.env
      - env/.auth.env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app # for hotreload
    networks:
      - backend-net

  db:
    build:
      context: .
      dockerfile: pg.Dockerfile
    image: fin-man-db
    container_name: fin-man-db
    volumes:
      - db:/data/db
    ports:
      - "5433:5432"
    restart: unless-stopped
    env_file:
      env/.db.env
    networks:
      - backend-net

networks:
  backend-net:
    name: backend
    driver: bridge

volumes:
  db:
